-- 항공편 좌석 분류 (그룹/인디비/비즈니스) 및 항공료 분류 (운임/유류할증료/발권피)
ALTER TABLE voyage_flights
  ADD COLUMN IF NOT EXISTS seats_group    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS seats_indivi   INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS seats_business INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fare_base      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fare_fuel      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fare_tax       INTEGER NOT NULL DEFAULT 0;
