-- flights 테이블 (새행사 등록용): 좌석 분류 + 항공료 분류 추가
ALTER TABLE flights
  ADD COLUMN IF NOT EXISTS seats_group    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS seats_indivi   INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS seats_business INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fare_base      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fare_fuel      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fare_tax       INTEGER NOT NULL DEFAULT 0;
